# Generated by Django 4.2 on 2026-04-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.BooleanField(default=True)),
                ('read_receipts', models.BooleanField(default=True)),
                ('notifications', models.BooleanField(default=True)),
                ('sound', models.BooleanField(default=True)),
                ('font_size', models.CharField(default='medium', max_length=10)),
                ('wallpaper', models.CharField(default='default', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
